version: '3.9'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderdb
    ports:
      - "3306:3306"
    platform: linux/amd64 # Optional: support for ARM/Intel

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    platform: linux/amd64

  order-service:
    build: ./order-service
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_DATABASE=18fx_assessment
      - RABBITMQ_URL=amqp://rabbitmq

  kitchen-service:
    build: ./kitchen-service
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_DATABASE=18fx_assessment
      - RABBITMQ_URL=amqp://rabbitmq

  notification-service:
    build: ./notification-service
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
